### ISSUE TITLE
Releasing PCB layout files?

### ISSUE THREAD

**Issue by joelburton** [config101/Bravo#2]
This is a really interesting project, and I've been enjoying the videos a lot.

Given the educational nature of this (and the fact you've licensed it as CC0), I was hoping to be able to find the PCB design files. It's helpful for me when debugging something I've put together, and it can also help us connect the physical boards to the schematics. It looks like the EasyEDA files don't have the PCBs in them (or perhaps I'm not looking at them properly?)

If your goal is to generate income from sales of the PCBs, I understand & can respect that. Perhaps just some screenshots of the boards and the routing can be provided? That can discourage people from bypassing buying them, but provide a lot of the understanding-the-system benefits.

**Comment by config101** [comment]
Hi Joel,
Thanks for your comment and I'm glad you are enjoying the videos.
You are right, the PCB files are not included in the EasyEDA files. 
While the project and all related circuits are licensed under Creative Commons, the PCBs are not. At this point, PCBs are commercial products sold at www.8bitkits.com.
This is really not about generating income from the project.The proceeds from the sale of PCBs/Kits are going into supporting current/future projects. Developing these PCBs has taken numerous hours of work and I went through 3 different prototypes/revisions over several months to come up with the final version that is all accurate and bug free.
Now, I have a plan to eventually release all the files which requires removing commercial markings from PCBs. That may happen in near future.
Here was my thought; if someone is hands on enough with building PCBs, all the schematics are available to do so. but If someone does not want to go that route, the PCBs are available for purchase and frankly the price that I'm offering the PCB sets at 8bitkits.com would probably be 30 to 40 percent less than cost of ordering PCBs from china (after cost of PCBs and shipping costs).
Anyhow, if you need the screenshots of the PCBs, I probably can take them. Just send me an email : support at 8bitkits.com and I will reply to that.
Thanks
CONFIG IOI
